#!/usr/bin/env python3
"""Bundle the small SVG battle atlas into a JS module for mobile offline rendering."""

import base64
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/assets/images"
TARGET = ROOT / "src/game/BattleArt.js"


def group(name):
    return {
        file.stem: "data:image/svg+xml;base64," + base64.b64encode(file.read_bytes()).decode("ascii")
        for file in sorted((ASSETS / name).glob("*.svg"))
    }


terrain = json.dumps(group("terrain"), separators=(",", ":"))
army = json.dumps(group("army"), separators=(",", ":"))
TARGET.write_text(
    "// Generated by scripts/bundle-battle-art.py. Keep the source SVG files as the editable artwork.\n"
    f"export const TERRAIN_ART = Object.freeze({terrain});\n"
    f"export const ARMY_ART = Object.freeze({army});\n",
    encoding="utf-8",
)
